site_name: Supplement – Context-Adaptive Distributions for Neural-Based Lossless Image Compression
site_description: Supplementary page with abstract and results for the paper "Context-Adaptive Distributions for Neural-Based Lossless Image Compression".
site_dir: site

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - content.code.copy
    - content.tabs.link
    - toc.integrate
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Results: results.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight

# repo_url: https://github.com/<usuario>/paper-supplement
# repo_name: <usuario>/paper-supplement
